apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello
  name: hello
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30000
  type: NodePort
  selector:
    run: hello
