apiVersion: v1
kind: Service
metadata:
  labels:
    run: now
    version: "2"
  name: now-v2
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30006
  type: NodePort
  selector:
    run: now
    version: "2"
