apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
    name: "http"
  - nodePort: 30002
    port: 443
    protocol: TCP
    targetPort: 443
    name: "https"
  selector:
    run: nginx
  type: LoadBalancer
